### ISSUE TITLE
使用该项目的时候，rpm包提示error，有别的代替吗

### ISSUE THREAD

**Issue by mozhu-too** [Ridter/warp_proxy#1]
当前项目不能用了，运行提示上图，有什么可替代的方法，或者其他的解决方案吗

**Comment by Ridter** [comment]
没看到图呢。

**Comment by mozhu-too** [comment]
等我明天回去给你截一个，我现在不在环境上

**Comment by mozhu-too** [comment]
![test](https://github.com/Ridter/warp_proxy/assets/108135476/3ea39f3e-5f8e-4823-a017-f01eb2fc231d)

**Comment by mozhu-too** [comment]
访问改链接已经404了

**Comment by Ridter** [comment]
好像确实是没了，等找到再发上来吧。

**Comment by mozhu-too** [comment]
好的，如果有新的方式，也请告诉我哈

**Comment by Ridter** [comment]
已更新，可以再试试～

**Comment by mozhu-too** [comment]
ok，等我更新了环境看看

**Comment by Ridter** [comment]
> ok，等我更新了环境看看

还有问题么？
